# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  name: "BusinessTools On-Prem Documentation"

steps:
- checkout: self
  clean: true
  submodules: true

- task: CmdLine@2 
  inputs:
    script: git clone http://tfs.infragistics.local:8080/tfs/Engineering/EnterpriseMobility/_git/RevealSdkApiDocs

- task: CmdLine@2
  displayName: Pull latest from the templates submodule
  inputs:
    script: 'git pull origin master'
    workingDirectory: 'templates/reveal'

- task: CmdLine@2 
  inputs:
    script: git clone http://tfs.infragistics.local:8080/tfs/Engineering/EnterpriseMobility/_git/RevealSdkApiDocs
- task: CmdLine@2
  inputs:
    script: |
      git submodule init 
      git submodule update
    workingDirectory: $(Build.SourcesDirectory)/RevealSdkApiDocs

- task: DocFxTask@0
  displayName: "Build Desktop Api docfx.json"
  inputs:
    solution: '$(Build.SourcesDirectory)/RevealSdkApiDocs/Desktop/docfx.json'

- task: DocFxTask@0
  displayName: "Build DotnetServer Api docfx.json"
  inputs:
    solution: '$(Build.SourcesDirectory)/RevealSdkApiDocs/DotnetServer/docfx.json'

- task: DocFxTask@0
  displayName: "Build docfx.json"
  inputs:
    solution: 'docfx.json'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/RevealSdkApiDocs'
    ArtifactName: 'debug_api_docs'
    publishLocation: 'pipeline'
    TargetPath: '\\igbgsofsmb2\builds\Reveal\Docs\$(Build.DefinitionName)\$(Build.BuildNumber)\EN'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '_site'
    ArtifactName: 'docs_site'
    publishLocation: 'FilePath'
    TargetPath: '\\igbgsofsmb2\builds\Reveal\Docs\$(Build.DefinitionName)\$(Build.BuildNumber)\EN'
    Parallel: true